###
POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "mohammadreza@gmail9.com",
    "password": "243123456",
    "name":"mohammadreza",
    "phoneNumber":"0917111111111"
}